# This Tutorial focuses on SciPy. 

SciPy - Scientific Python is a free opensource scientific computation library. It provides utility functions for optimization, statistics and signal processing.

For references, check its [documentation](https://docs.scipy.org/doc/scipy/tutorial/index.html).


In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


#Question1. 
Calculate the L1 & L2 norm for a random 3*3 generated matrix

In [ ]:
import numpy as np
from scipy.linalg import norm

data = np.random.randint(0,10,size = 9).reshape(3,3)
# a = np.matrix(data)

print(data)
norm1 = norm(data,1)

print(norm1)

# For L2 Norm

norm2 = norm(data)
print("Norm 2 :\n",norm2)

[[7 2 7]
 [3 9 9]
 [3 4 6]]
22.0
Norm 2 :
 18.275666882497067


#Question2.
Find the value of a & b using scipy's least-square solution function for the relation $y = a + bx^3$ using the following data points:

    x = np.array([1, 3, 4, 5, 6, 7, 9])
    y = np.array([0.3, 1.4, 1.7, 2.4, 3.5, 6.7, 9.4])

Also, plot the graph containing the x & y points and the final function

#Question 3.
 Use scipy.io function to read in a .mat file, extract the data from the file and use it to fit the function (y = a+bx)? Create a .mat file containing the following data (Hint: Use scipy.io)

    x_data = [1, 2, 3, 4, 5]
    y_data = [3, 5, 7, 9, 11]


# Question 4.
Solve the set of linear equations using scipy.
$$
x + y + z = 9
$$
$$
2x – y + z = 5
$$
$$
4x + y – z = 7
$$

In [ ]:
import numpy as np
from scipy import linalg

A = [
    [1,1,1],
    [2,1,1],
    [4,1,-1]
]
b = np.array([9,5,7]).reshape(3,1)
ans = linalg.solve(A,b)
ans

array([[-4.],
       [18.],
       [-5.]])

#Question 5.
Using numpy, create an array consisting of the numbers from 1 to 20 and use scipy to generate its fast fourier transformation.
Also find its inverse transformation.

In [ ]:
a = np.arange(1,20)
from scipy.fft import fft,ifft
x = fft(a)
print('FFT of a: \n', x)

inverse = ifft(a)
print('Inverse Transformation: \n', inverse)


FFT of a: 
 [190.  -0.j          -9.5+56.93037886j  -9.5+27.67255462j
  -9.5+17.55446244j  -9.5+12.20560025j  -9.5 +8.74536608j
  -9.5 +6.20665977j  -9.5 +4.16708636j  -9.5 +2.40572673j
  -9.5 +0.78719244j  -9.5 -0.78719244j  -9.5 -2.40572673j
  -9.5 -4.16708636j  -9.5 -6.20665977j  -9.5 -8.74536608j
  -9.5-12.20560025j  -9.5-17.55446244j  -9.5-27.67255462j
  -9.5-56.93037886j]
Inverse Transformation: 
 [10. -0.j         -0.5-2.99633573j -0.5-1.45645024j -0.5-0.92391908j
 -0.5-0.64240001j -0.5-0.46028243j -0.5-0.3266663j  -0.5-0.21932033j
 -0.5-0.1266172j  -0.5-0.04143118j -0.5+0.04143118j -0.5+0.1266172j
 -0.5+0.21932033j -0.5+0.3266663j  -0.5+0.46028243j -0.5+0.64240001j
 -0.5+0.92391908j -0.5+1.45645024j -0.5+2.99633573j]


#Question 6

Similar to the previous question, but now, generate FFT of a 2D array.

Create a random integer array of size 4*5 and use scipy to find its Fast Fourier transformation and also find the inverse of the resulting array (FFT).

In [ ]:
arr = np.random.randint(1,50,20).reshape(4,5)

from scipy.fft import fft,ifft
print ('Generated Array \n',arr)

newfft = fft(arr)

print('Fft :\n', newfft)

newinverse = ifft(newfft)
print('Inverse :\n', newinverse)

Generated Array 
 [[ 3 19  5 23  9]
 [47 33  6  4 38]
 [37 20 46 35 21]
 [40 45 16 24 28]]
Fft :
 [[ 59.         -0.j         -11.         +1.06956938j
  -11.        -22.99686982j -11.        +22.99686982j
  -11.         -1.06956938j]
 [128.         -0.j          60.85003666 +3.57971208j
   -7.35003666 +4.84103929j  -7.35003666 -4.84103929j
   60.85003666 -3.57971208j]
 [159.         -0.j         -15.86067977 -5.51458126j
   28.86067977+11.04940693j  28.86067977-11.04940693j
  -15.86067977 +5.51458126j]
 [153.         -0.j          30.19756081-11.46567876j
   -6.69756081-17.60080142j  -6.69756081+17.60080142j
   30.19756081+11.46567876j]]
Inverse :
 [[ 3.+0.j 19.+0.j  5.+0.j 23.+0.j  9.+0.j]
 [47.+0.j 33.+0.j  6.+0.j  4.+0.j 38.+0.j]
 [37.+0.j 20.+0.j 46.+0.j 35.+0.j 21.+0.j]
 [40.+0.j 45.+0.j 16.+0.j 24.+0.j 28.+0.j]]


#Question 7.
Create a sine wave with a frequency of 50Hz and apply FFT on it. Plot the result using matplotlib. 